steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - '_NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
    - '_NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["run", "deploy"]
timeout: "1600s"