name: nextjs-cloud-run

on:
  push:
    branches:
      - master
      - main

env:
  CLOUD_RUN_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
  NEXT_PUBLIC_STRIPE_PRICE_MONTH_PROMOTE: ${{ secrets.NEXT_PUBLIC_STRIPE_PRICE_MONTH_PROMOTE }}
  CLOUD_RUN_REGION: europe-west1
  # project-name but it can be anything you want
  REPO_NAME: aboutdata-website

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # This step is where our service account will be authenticated
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        service_account_email: ${{ secrets.GCP_EMAIL }}

    - name: Enable the necessary APIs and enable docker auth
      run: |-
        gcloud --quiet auth configure-docker
    - name: Build and tag image
      run: |-
        docker build . --build-arg 'NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}' --build-arg 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}' --build-arg 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}' --build-arg 'STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}' --build-arg 'STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}' --build-arg 'NEXT_PUBLIC_STRIPE_PRICE_MONTH_PROMOTE=${{ secrets.NEXT_PUBLIC_STRIPE_PRICE_MONTH_PROMOTE }}' --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
    - name: Push image to GCR
      run: |-
        docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA
    - name: Deploy
      run: |-
        gcloud components install beta --quiet
        gcloud beta run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --project $CLOUD_RUN_PROJECT_ID \
          --platform managed \
          --region $CLOUD_RUN_REGION \
          --allow-unauthenticated \
          --no-cpu-throttling \
          --quiet
